-- Schema generated by truss. DO NOT EDIT.

CREATE TABLE `migrations` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `query_hash` char(64) COLLATE utf8mb4_general_ci NOT NULL,
  `schema_hash` char(64) COLLATE utf8mb4_general_ci NOT NULL,
  `created_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci

CREATE TABLE `replay_events` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `key` varchar(512) COLLATE utf8mb4_general_ci NOT NULL,
  `namespace` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `workflow` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `run` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `iteration` int NOT NULL,
  `type` int NOT NULL,
  `timestamp` datetime(3) NOT NULL,
  `message` mediumblob,
  PRIMARY KEY (`id`),
  UNIQUE KEY `by_type_key` (`type`,`key`),
  KEY `type` (`type`,`namespace`,`workflow`,`run`,`iteration`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci

CREATE TABLE `replay_signal_awaits` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `key` varchar(512) COLLATE utf8mb4_general_ci NOT NULL,
  `created_at` datetime(3) NOT NULL,
  `timeout_at` datetime(3) NOT NULL,
  `status` tinyint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `by_key` (`key`),
  KEY `status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci

CREATE TABLE `replay_signals` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `namespace` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `hash` binary(128) NOT NULL,
  `workflow` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `run` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `signal` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `external_id` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `message` mediumblob,
  `created_at` datetime(3) NOT NULL,
  `check_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq` (`namespace`,`hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci

CREATE TABLE `replay_sleeps` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `key` varchar(512) COLLATE utf8mb4_general_ci NOT NULL,
  `created_at` datetime(3) NOT NULL,
  `complete_at` datetime(3) NOT NULL,
  `completed` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `by_key` (`key`),
  KEY `completed` (`completed`,`complete_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci