// Code generated by protoc-gen-go. DO NOT EDIT.
// source: replay.proto

package internal

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SleepDone struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SleepDone) Reset()         { *m = SleepDone{} }
func (m *SleepDone) String() string { return proto.CompactTextString(m) }
func (*SleepDone) ProtoMessage()    {}
func (*SleepDone) Descriptor() ([]byte, []int) {
	return fileDescriptor_eed9461330ccfc03, []int{0}
}

func (m *SleepDone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SleepDone.Unmarshal(m, b)
}
func (m *SleepDone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SleepDone.Marshal(b, m, deterministic)
}
func (m *SleepDone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SleepDone.Merge(m, src)
}
func (m *SleepDone) XXX_Size() int {
	return xxx_messageInfo_SleepDone.Size(m)
}
func (m *SleepDone) XXX_DiscardUnknown() {
	xxx_messageInfo_SleepDone.DiscardUnknown(m)
}

var xxx_messageInfo_SleepDone proto.InternalMessageInfo

type SleepRequest struct {
	Duration             *duration.Duration `protobuf:"bytes,1,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SleepRequest) Reset()         { *m = SleepRequest{} }
func (m *SleepRequest) String() string { return proto.CompactTextString(m) }
func (*SleepRequest) ProtoMessage()    {}
func (*SleepRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eed9461330ccfc03, []int{1}
}

func (m *SleepRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SleepRequest.Unmarshal(m, b)
}
func (m *SleepRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SleepRequest.Marshal(b, m, deterministic)
}
func (m *SleepRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SleepRequest.Merge(m, src)
}
func (m *SleepRequest) XXX_Size() int {
	return xxx_messageInfo_SleepRequest.Size(m)
}
func (m *SleepRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SleepRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SleepRequest proto.InternalMessageInfo

func (m *SleepRequest) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func init() {
	proto.RegisterType((*SleepDone)(nil), "internal.SleepDone")
	proto.RegisterType((*SleepRequest)(nil), "internal.SleepRequest")
}

func init() { proto.RegisterFile("replay.proto", fileDescriptor_eed9461330ccfc03) }

var fileDescriptor_eed9461330ccfc03 = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4a, 0x2d, 0xc8,
	0x49, 0xac, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xc8, 0xcc, 0x2b, 0x49, 0x2d, 0xca,
	0x4b, 0xcc, 0x91, 0x92, 0x4b, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x8b, 0x27, 0x95, 0xa6,
	0xe9, 0xa7, 0x94, 0x16, 0x25, 0x96, 0x64, 0xe6, 0xe7, 0x41, 0x54, 0x2a, 0x71, 0x73, 0x71, 0x06,
	0xe7, 0xa4, 0xa6, 0x16, 0xb8, 0xe4, 0xe7, 0xa5, 0x2a, 0xb9, 0x72, 0xf1, 0x80, 0x39, 0x41, 0xa9,
	0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0xa6, 0x5c, 0x1c, 0x30, 0xe5, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0xdc, 0x46, 0x92, 0x7a, 0x10, 0xf3, 0xf4, 0x60, 0xe6, 0xe9, 0xb9, 0x40, 0x15, 0x04, 0xc1, 0x95,
	0x26, 0xb1, 0x81, 0x25, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x74, 0x37, 0x7d, 0x94,
	0x00, 0x00, 0x00,
}
